Users table
kamil3397/todo-react-app pull request #19
Opened 2024-10-18 20:00 UTC by kamil3397

Z badgem był problem nie rozgryzłem jak go ruszyć bo zaczął się ruszać z nim cały button ale dla Box zwiekszylem padding co i tak mialo byc zrobione i automatycznie badge zaczal sie mieścić

2024-10-23 11:01 UTC, sseler requested changes

2024-10-23 11:01 UTC, sseler commented on src/theme/theme.ts
> +    // }
```suggestion
```

2024-10-23 11:01 UTC, sseler commented on src/types/ListTypes.ts
> +// SOLID - Interface Segregation Principle!!!
jest komentarz, ale dalej nie widze jakichkolwiek zmian w odniesieniu do niego (zwazywszy na nazwe plikow ListTypes, do ktorego dodajesz enum UserRoles)

2024-10-27 18:06 UTC, kamil3397 commented on src/App.tsx
> +import UserTasksPreview from 'pages/Users/UserProfile/components/UserTasksPreview';
zostawione nieumyślnie, nie powinno być tego importu

2024-10-27 22:03 UTC, kamil3397 commented
@sseler sprawdź proszę czy o to chodziło z tym useEffect w UserTaskPreview

2024-10-27 22:04 UTC, kamil3397 commented on src/pages/Users/UserProfile.tsx
> +        userHasPermissions(['assignRole']).then((res) => setHasAssignRolePermission(res))
@sseler tutaj chyba nie kumam 🐸

2024-10-28 12:49 UTC, sseler requested changes

2024-10-28 12:49 UTC, sseler commented on src/pages/Users/UserProfile.tsx
> +        userHasPermissions(['assignRole']).then((res) => setHasAssignRolePermission(res))
no przeciez napisalem w komentarzu jak to powinno wygladac. 
Powinien to byc hook => useHasPermissions
potem w kodzie: 
const userHasPermissions = useHasPermissions(['assignRole']);

Nie powinienes robic tutaj dodatkowego useState'a, to hook Ci juz zalatwia.

2024-10-28 12:49 UTC, sseler commented on src/pages/Users/UserProfile/components/UserTasksPreview.tsx
> +    // }, [userId]);
```suggestion
```

2024-10-28 12:49 UTC, sseler commented on src/pages/Users/UserProfile/components/UserTasksPreview.tsx
> +        fetchTasks()
po co pakujesz to w oddzielne funkcje skoro nie sa one asynchroniczne tak czy siak? Dodatkowo mozna by to wpakowac w Promise.all

2024-10-28 12:49 UTC, sseler commented on src/pages/Users/UserProfile/components/UserTasksPreview.tsx
> +        fetchTasks()
Nie sa asynchroniczne, bo nie uzywasz ani async ani await*

2024-10-28 12:49 UTC, sseler commented on src/types/UserTypes.ts
> +export type LogourData = {
```suggestion
export type LogoutData = {
```

2024-10-28 12:49 UTC, sseler commented on src/types/UserTypes.ts
> +export type LogourData = {
typ, ktory ma jeden klucz nie jest jakos super potrzebny, ale niech juz zostanie

2024-10-28 12:49 UTC, sseler commented on src/types/UserTypes.ts
> +export type LoginInputs = {
```suggestion
export type LoginData= {
```

2024-10-28 12:49 UTC, sseler commented on src/types/UserTypes.ts
> +export type RegistrationData = {
```suggestion
export type RegisterData = {
```

2024-10-28 12:49 UTC, sseler commented on src/types/UserTypes.ts
> +}
rozni sie to od UserType tylko brakiem roli.
```suggestion
export type EditUserType = Omit<UserType, 'role'>
```
w zasadzie nie musisz go robisz tu globalnie, a jedynie uzyc tego Omita tam gdzie submittujesz dane

2024-11-06 12:51 UTC, merged